In [1]:
import numpy as np

an_array = np.array([3, 33, 333])
print(type(an_array))

<class 'numpy.ndarray'>


In [2]:
print(an_array.shape)

(3,)


In [3]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [4]:
an_array[0] = 888

In [5]:
print(an_array)

[888  33 333]


In [6]:
another = np.array([[11, 12, 13], [21, 22, 23]])
print(another)

[[11 12 13]
 [21 22 23]]


In [7]:
print('the shape is: ', another.shape)

the shape is:  (2, 3)


In [8]:
print('Elements [0,0], [0,1], [1,0]: ', another[0,0], another[0,1], another[1,0])

Elements [0,0], [0,1], [1,0]:  11 12 21


In [9]:
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [10]:
ex2 = np.full((3,3), 9)
print(ex2)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [11]:
ex3 = np.eye(2, 2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [12]:
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [13]:
print(ex4.shape)

(1, 2)


In [14]:
print(ex4[0,1])

1.0


In [15]:
ex5 = np.random.random((2,2))

In [16]:
print(ex5)

[[0.02720933 0.85385574]
 [0.38159162 0.35149011]]


In [17]:
an_array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [18]:
# a_slice = an_array[:2, 1:3]
a_slice = np.array(an_array[:2, 1:3])
print(a_slice)

[[12 13]
 [22 23]]


In [19]:
print(a_slice)

[[12 13]
 [22 23]]


In [20]:
print(a_slice[0][0])

12


In [21]:
print(an_array[0,1])

12


In [22]:
a_slice[0,0] = 1000

In [23]:
print(an_array[0,1])

12


In [24]:
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [25]:
row_rank1 = an_array[1, :]

In [26]:
print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [27]:
row_rank2 = an_array[1:2, :]
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [28]:
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]
print(col_rank1, col_rank1.shape)
print()
print(col_rank2, col_rank2.shape)

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [29]:
an_array = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
print(an_array)
col_indices = np.array([0, 1, 2, 0])
print('\n Col indices picked: ', col_indices)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]

 Col indices picked:  [0 1 2 0]


In [30]:
row_indices = np.arange(4)
print('\n Row indices picked: ', row_indices)


 Row indices picked:  [0 1 2 3]


In [31]:
for row, col in zip(row_indices, col_indices):
    print(row, ", ", col)
    
print(an_array)

0 ,  0
1 ,  1
2 ,  2
3 ,  0
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [32]:
print('Values in the array at those indices: ', an_array[row_indices, col_indices])

Values in the array at those indices:  [11 22 33 41]


In [33]:
an_array[row_indices, col_indices] += 100000
print(an_array)

[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


In [34]:
array = np.random.random((3,3))

In [35]:
print(array)

[[0.04887271 0.80253895 0.60652034]
 [0.30974324 0.72595773 0.30875751]
 [0.13960345 0.31003981 0.93151754]]


In [36]:
print(array[:2,])

[[0.04887271 0.80253895 0.60652034]
 [0.30974324 0.72595773 0.30875751]]


In [37]:
an_array = np.array([[11, 12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [38]:
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [39]:
print(an_array[filter])

[21 22 31 32]


In [40]:
print(an_array[(an_array > 20) & (an_array < 30)])

[21 22]


In [41]:
print(an_array[(an_array % 2 == 0)])

[12 22 32]


In [42]:
an_array[(an_array  % 2 == 0)]  += 100

In [43]:
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [44]:
ex1 = np.array([11, 12])
print(ex1.dtype)

ex2 = np.array([11.0, 12.0])
print(ex2.dtype)

ex3 = np.array([11, 21], dtype=np.int64)
print(ex3.dtype)

ex4 = np.array([11.1, 12.7], dtype=np.int64)
print(ex4.dtype)
print(ex4)

int32
float64
int64
int64
[11 12]


In [45]:
ex5 = np.array([11, 21], dtype=np.float64)

In [46]:
print(ex5)

[11. 21.]


In [47]:
x = np.array([[111, 112], [121, 122]], dtype=np.int)
y = np.array([[211.1, 212.1], [221.1, 222.1]], dtype=np.float64)
print(x)
print(y)

[[111 112]
 [121 122]]
[[211.1 212.1]
 [221.1 222.1]]


In [48]:
print(x + y)

[[322.1 324.1]
 [342.1 344.1]]


In [49]:
print(np.add(x, y))

[[322.1 324.1]
 [342.1 344.1]]


In [50]:
 print(x - y)

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [51]:
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [52]:
print(x * y)

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [53]:
print( x/y)

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [54]:
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [55]:
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [56]:
arr = 10 * np.random.random((2,4))
print(arr)

[[5.20850282 2.36341673 1.24836748 5.40392844]
 [3.61599901 0.46136316 7.62019403 7.53441487]]


In [57]:
arr2 = 10 * np.random.randn(2,4)

In [58]:
print(arr2
     )

[[ -5.5413989    3.30952662 -11.62154367  -4.43582013]
 [-26.35867718  -4.81535401   6.25900439   2.73768191]]


In [59]:
print(arr.mean())

4.182023316939704


In [60]:
print(arr.mean(axis = 1))

[3.55605387 4.80799277]


In [61]:
print(arr.mean(axis = 0))

[4.41225091 1.41238994 4.43428076 6.46917166]


In [62]:
print(arr.sum())

33.45618653551763


In [63]:
print(np.median(arr, axis = 1))

[3.78595977 5.57520694]


In [64]:
unsorted = np.random.randn(10)

In [65]:
print(unsorted)

[-0.28211963 -1.05813409 -0.0838803  -0.00918285 -0.5126417   0.23093178
  1.06877756  0.65902563 -0.07709463 -1.42939408]


In [66]:
sorted = np.array(unsorted)
sorted.sort()
print(sorted)
print(unsorted)

[-1.42939408 -1.05813409 -0.5126417  -0.28211963 -0.0838803  -0.07709463
 -0.00918285  0.23093178  0.65902563  1.06877756]
[-0.28211963 -1.05813409 -0.0838803  -0.00918285 -0.5126417   0.23093178
  1.06877756  0.65902563 -0.07709463 -1.42939408]


In [67]:
unsorted.sort()
print(unsorted)

[-1.42939408 -1.05813409 -0.5126417  -0.28211963 -0.0838803  -0.07709463
 -0.00918285  0.23093178  0.65902563  1.06877756]


In [68]:
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


In [69]:
s1 = np.array(['desk', 'chair', 'bulb'])
s2 = np.array(['lamp', 'bulb', 'chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [70]:
print(np.intersect1d(s1, s2))

['bulb' 'chair']


In [71]:
print(np.union1d(s1, s2))

['bulb' 'chair' 'desk' 'lamp']


In [72]:
print(np.setdiff1d(s1, s2))

['desk']


In [73]:
print(np.in1d(s1, s2
                 ))

[False  True  True]


In [74]:
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [75]:
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [76]:
y = start + add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [77]:
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [78]:
y = start+ add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [79]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [80]:
print(start + 1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [81]:
print(start + np.array([1]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a = np.array([[0,0], [0,0]])
b1 = np.array([1,1])
b2 = 1
print(a + b1)
print(a + b2)

In [1]:
from numpy import arange
from timeit import Timer

size = 1000000
timeits = 1000

nd_array = arange(size)
print(nd_array)

[     0      1      2 ... 999997 999998 999999]


In [2]:
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")
print("Time taken by numpy ndarray: %f seconds" % (timer_numpy.timeit(timeits) / timeits))

Time taken by numpy ndarray: 0.000305 seconds


In [3]:
a_list = list(range(size))
print(type(a_list))

<class 'list'>


In [4]:
timer_list = Timer("sum(a_list)", "from __main__ import a_list")
print("Time taken by list: %f seconds" % (timer_list.timeit(timeits) / timeits))

Time taken by list: 0.021139 seconds
