In [2]:
import numpy as np

an_array = np.array([3, 33, 333])
print(type(an_array))

<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [4]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [5]:
an_array[0] = 888

In [6]:
print(an_array)

[888  33 333]


In [7]:
another = np.array([[11, 12, 13], [21, 22, 23]])
print(another)

[[11 12 13]
 [21 22 23]]


In [8]:
print('the shape is: ', another.shape)

the shape is:  (2, 3)


In [9]:
print('Elements [0,0], [0,1], [1,0]: ', another[0,0], another[0,1], another[1,0])

Elements [0,0], [0,1], [1,0]:  11 12 21


In [10]:
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [11]:
ex2 = np.full((3,3), 9)
print(ex2)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [12]:
ex3 = np.eye(2, 2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [13]:
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [14]:
print(ex4.shape)

(1, 2)


In [15]:
print(ex4[0,1])

1.0


In [16]:
ex5 = np.random.random((2,2))

In [17]:
print(ex5)

[[0.86397787 0.9376411 ]
 [0.46579539 0.46526348]]


In [18]:
an_array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [27]:
# a_slice = an_array[:2, 1:3]
a_slice = np.array(an_array[:2, 1:3])
print(a_slice)

[[12 13]
 [22 23]]


In [28]:
print(a_slice)

[[12 13]
 [22 23]]


In [29]:
print(a_slice[0][0])

12


In [30]:
print(an_array[0,1])

12


In [31]:
a_slice[0,0] = 1000

In [32]:
print(an_array[0,1])

12


In [33]:
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [34]:
row_rank1 = an_array[1, :]

In [35]:
print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [36]:
row_rank2 = an_array[1:2, :]
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [39]:
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]
print(col_rank1, col_rank1.shape)
print()
print(col_rank2, col_rank2.shape)

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [53]:
an_array = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
print(an_array)
col_indices = np.array([0, 1, 2, 0])
print('\n Col indices picked: ', col_indices)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]

 Col indices picked:  [0 1 2 0]


In [47]:
row_indices = np.arange(4)
print('\n Row indices picked: ', row_indices)


 Row indices picked:  [0 1 2 3]


In [55]:
for row, col in zip(row_indices, col_indices):
    print(row, ", ", col)
    
print(an_array)

0 ,  0
1 ,  1
2 ,  2
3 ,  0
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [54]:
print('Values in the array at those indices: ', an_array[row_indices, col_indices])

Values in the array at those indices:  [11 22 33 41]
