In [2]:
import numpy as np

an_array = np.array([3, 33, 333])
print(type(an_array))

<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [4]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [8]:
an_array[0] = 888

In [6]:
print(an_array)

[888  33 333]


In [9]:
another = np.array([[11, 12, 13], [21, 22, 23]])
print(another)

[[11 12 13]
 [21 22 23]]


In [10]:
print('the shape is: ', another.shape)

the shape is:  (2, 3)


In [12]:
print('Elements [0,0], [0,1], [1,0]: ', another[0,0], another[0,1], another[1,0])

Elements [0,0], [0,1], [1,0]:  11 12 21


In [14]:
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [16]:
ex2 = np.full((3,3), 9)
print(ex2)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [20]:
ex3 = np.eye(2, 2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [22]:
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [23]:
print(ex4.shape)

(1, 2)


In [24]:
print(ex4[0,1])

1.0


In [25]:
ex5 = np.random.random((2,2))

In [26]:
print(ex5)

[[0.71844958 0.02037279]
 [0.10668114 0.3489214 ]]


In [30]:
an_array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [38]:
# a_slice = an_array[:2, 1:3]
a_slide = np.array(an_array[:2, 1:3])

In [40]:
print(a_slice)

[[1000   13]
 [  22   23]]


In [41]:
print(a_slice[0][0])

1000


In [42]:
print(an_array[0,1])

1000


In [43]:
a_slice[0,0] = 1000

In [44]:
print(an_array[0,1])

1000


In [45]:
print(an_array)

[[  11 1000   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]


In [46]:
row_rank1 = an_array[1, :]

In [47]:
print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [50]:
row_rank2 = an_array[1:2, :]
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [ ]:
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]
print(col_rank1, col_rank)